display_information:
  name: WebPollBot
  description: Manage poll website of CO-WELL
  background_color: "#6b6304"
features:
  bot_user:
    display_name: WebPollBot
    always_online: false
oauth_config:
  scopes:
    user:
      - users:read
      - users:read.email
    bot:
      - users:read
      - users:read.email
      - team:read
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
